In [ ]:
#Numerical Python ->

In [1]:
import numpy as np
print(np.__version__)

2.4.4


In [3]:
l= [2,5,6,7,11]
print(l)
a= np.array(l)
print(a)

[2, 5, 6, 7, 11]
[ 2  5  6  7 11]


In [5]:
l1= [[1,2,3],[4,5,6],[7,8,9]]
print(l1)
b= np.array(l1)
print(b)

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [7]:
l2= [[[1,2,4],[3,4,1],[5,6,6],[3,6,1]],[[7,8,1],[9,10,9],[3,12,1],[7,5,2]],[[1,2,4],[3,4,1],[5,6,6],[3,6,1]]]
print(l2)
c= np.array(l2)
print(c)

[[[1, 2, 4], [3, 4, 1], [5, 6, 6], [3, 6, 1]], [[7, 8, 1], [9, 10, 9], [3, 12, 1], [7, 5, 2]], [[1, 2, 4], [3, 4, 1], [5, 6, 6], [3, 6, 1]]]
[[[ 1  2  4]
  [ 3  4  1]
  [ 5  6  6]
  [ 3  6  1]]

 [[ 7  8  1]
  [ 9 10  9]
  [ 3 12  1]
  [ 7  5  2]]

 [[ 1  2  4]
  [ 3  4  1]
  [ 5  6  6]
  [ 3  6  1]]]


In [10]:
o=np.arange(10)
print(o)
o1= np.arange(1,16)
print(o1)
o2= np.arange(1,101,3)
print(o2)

[0 1 2 3 4 5 6 7 8 9]
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]
[  1   4   7  10  13  16  19  22  25  28  31  34  37  40  43  46  49  52
  55  58  61  64  67  70  73  76  79  82  85  88  91  94  97 100]


In [13]:
x= np.linspace(0,10,5)
print(x)

[ 0.   2.5  5.   7.5 10. ]


In [14]:
x1= np.linspace(0,100,20)
print(x1)

[  0.           5.26315789  10.52631579  15.78947368  21.05263158
  26.31578947  31.57894737  36.84210526  42.10526316  47.36842105
  52.63157895  57.89473684  63.15789474  68.42105263  73.68421053
  78.94736842  84.21052632  89.47368421  94.73684211 100.        ]


In [20]:
o2=np.zeros(5)
print(o2)
o3=np.zeros((5,5))
print(o3)
o4=np.zeros((5,5,5))
print(o4)

[0. 0. 0. 0. 0.]
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
[[[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]]


In [22]:
o2=np.ones(5)
print(o2)
o3=np.ones((5,5))
print(o3)
o4=np.ones((5,5,5))
print(o4)

[1. 1. 1. 1. 1.]
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]]


In [24]:
o2=np.twos(5)
print(o2)

AttributeError: module 'numpy' has no attribute 'twos'

In [26]:
o6=np.full((3,4,3),17)
print(o6)

[[[17 17 17]
  [17 17 17]
  [17 17 17]
  [17 17 17]]

 [[17 17 17]
  [17 17 17]
  [17 17 17]
  [17 17 17]]

 [[17 17 17]
  [17 17 17]
  [17 17 17]
  [17 17 17]]]


In [29]:
i= np.eye(7) #identical matrix
print(i)
d= np.diag([4,7,9,2,3]) #diagonal matrix
print(d)

[[1. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 1.]]
[[4 0 0 0 0]
 [0 7 0 0 0]
 [0 0 9 0 0]
 [0 0 0 2 0]
 [0 0 0 0 3]]


In [35]:
ra= np.random.random((5,4))
print(ra)
ra1= np.random.randint(0,25,(5,5))
print(ra1)

[[0.57509628 0.50353878 0.59072776 0.6334088 ]
 [0.31611962 0.9123209  0.08757592 0.99582715]
 [0.82274973 0.51099411 0.98094974 0.19820148]
 [0.30892736 0.38414109 0.89323463 0.894535  ]
 [0.57239315 0.92585249 0.20354402 0.39932248]]
[[10 21  8  9 15]
 [13 14  1  7 19]
 [20 10 18 15 23]
 [14 11 18 14  5]
 [18 14 22 24  4]]


In [37]:
# Single dimension
import numpy as np
# total for five students
total = []
for i in range(0, 5):
    a = int(input(f"Student {i+1}, Total = "))
    total.append(a)
output = np.array(total)
print(total)
print(output)

[23, 55, 23, 78, 12]
[23 55 23 78 12]


In [38]:
#Two dimension
#average of 5 students marks in 5 subjects
import numpy as np
li=[]
avg=[]
for i in range(0,5): #5 students
    li1=[]
    sum=0
    for j in range(0,5): #5 subject marks
        a=int(input(f"Student{i+1}, Mark in sub{j+1}"))
        li1.append(a)
        sum+=a
    li.append(li1)
    avg.append(sum/5)
print("List representation:\n",li)
arr=np.array(li)
print("Array representation: \n",arr)
print(avg)

List representation:
 [[85, 75, 45, 97, 56], [88, 67, 88, 76, 88], [91, 82, 92, 83, 79], [93, 74, 56, 61, 49], [99, 87, 68, 77, 63]]
Array representation: 
 [[85 75 45 97 56]
 [88 67 88 76 88]
 [91 82 92 83 79]
 [93 74 56 61 49]
 [99 87 68 77 63]]
[71.6, 81.4, 85.4, 66.6, 78.8]


In [39]:
#Three dimension
import numpy as np
no_students= int(input("Enter number of students: "))
no_semesters= int(input("Enter number of semesters: "))
no_subjects= int(input("Enter number of subjects: "))
p_list=[]
for i in range(0,no_students):
    sem_list=[]
    for j in range(0, no_semesters):
        marks_list=[]
        for k in range(0, no_subjects):
            m=int(input(f"Student: {i+1} Semester: {j+1}, Enter mark in subject {k+1}: "))
            marks_list.append(m)
        sem_list.append(marks_list)
    p_list.append(sem_list)
print(p_list)
print(np.array(p_list))

[[[71, 63, 91, 78], [74, 67, 66, 57], [99, 71, 78, 64]]]
[[[71 63 91 78]
  [74 67 66 57]
  [99 71 78 64]]]


In [47]:
# ── From Python lists ──────────────────────────────────────────────────────────
a1d = np.array([10, 20, 30, 40, 50])
a2d = np.array([[1, 2, 3],
                [4, 5, 6]])
a3d = np.array([[[1,2],[3,4]],
                [[5,6],[7,8]]])

print("1-D:", a1d)
print("2-D:\n", a2d)
print("3-D shape:", a3d.shape)
print(a1d.ndim)
print(a2d.ndim)
print(a3d.ndim)

1-D: [10 20 30 40 50]
2-D:
 [[1 2 3]
 [4 5 6]]
3-D shape: (2, 2, 2)
1
2
3


In [48]:
# ── Zeros, Ones, Full, Eye, Identity ──────────────────────────────────────────
print("zeros(3,4):\n",    np.zeros((3, 4)))
print("ones(2,5):\n",     np.ones((2, 5)))
print("full(3,3, 7):\n",  np.full((3, 3), fill_value=7))
print("eye(4):\n",        np.eye(4))
print("identity(3):\n",   np.identity(3))
print("empty(2,3):\n",    np.empty((2, 3)))      # uninitialized — fast

zeros(3,4):
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
ones(2,5):
 [[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
full(3,3, 7):
 [[7 7 7]
 [7 7 7]
 [7 7 7]]
eye(4):
 [[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
identity(3):
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
empty(2,3):
 [[4.9e-324 9.9e-324 1.5e-323]
 [2.0e-323 2.5e-323 3.0e-323]]


In [2]:
# ── Ranges & Sequences ────────────────────────────────────────────────────────

# arange — like Python range but returns ndarray
print("arange(0,20,2):", np.arange(0, 20, 2))

# linspace — N evenly-spaced points between start & stop (inclusive)
print("linspace(0,1,6):", np.linspace(0, 1, 6))

# logspace — evenly spaced on a log scale (great for hyperparameter grids)
print("logspace(0,3,4):", np.logspace(0, 3, 4, base= 10))   # 10^0 … 10^3. Default Base value= 10

# geomspace — geometric sequence
print("geomspace(1,1000,4):", np.geomspace(1, 1000, 4))

# meshgrid — build coordinate grids (used in contour/surface plots)
x = np.linspace(-2, 2, 5)
print("X: ",x)
y = np.linspace(-2, 2, 5)
print("Y: ",y)
XX, YY = np.meshgrid(x, y)
print("meshgrid XX:\n", XX)
print(YY)

arange(0,20,2): [ 0  2  4  6  8 10 12 14 16 18]
linspace(0,1,6): [0.  0.2 0.4 0.6 0.8 1. ]
logspace(0,3,4): [   1.   10.  100. 1000.]
geomspace(1,1000,4): [   1.   10.  100. 1000.]
X:  [-2. -1.  0.  1.  2.]
Y:  [-2. -1.  0.  1.  2.]
meshgrid XX:
 [[-2. -1.  0.  1.  2.]
 [-2. -1.  0.  1.  2.]
 [-2. -1.  0.  1.  2.]
 [-2. -1.  0.  1.  2.]
 [-2. -1.  0.  1.  2.]]
[[-2. -2. -2. -2. -2.]
 [-1. -1. -1. -1. -1.]
 [ 0.  0.  0.  0.  0.]
 [ 1.  1.  1.  1.  1.]
 [ 2.  2.  2.  2.  2.]]


In [9]:
arr = np.random.randn(1000, 50).astype(np.float32)
print(arr)
print(f"ndim        : {arr.ndim}")           # number of dimensions
print(f"shape       : {arr.shape}")          # (rows, cols)
print(f"size        : {arr.size:,}")         # total elements
print(f"dtype       : {arr.dtype}")          # data type
print(f"itemsize    : {arr.itemsize} bytes") # bytes per element
print(f"nbytes      : {arr.nbytes/1024:.1f} KB")  # total memory

[[ 1.5327792   1.4693588   0.15494743 ... -0.6848101  -0.87079716
  -0.5788497 ]
 [-0.31155252  0.05616534 -1.1651498  ... -0.14963454 -0.43515354
   1.8492638 ]
 [ 0.67229474  0.40746182 -0.76991606 ...  0.6815945  -0.80340964
  -0.6895498 ]
 ...
 [ 0.48661712 -0.47508827  0.9606439  ... -2.3725543   0.8668217
  -0.5885546 ]
 [-2.0502036   0.1267352  -1.3493905  ... -0.3932261  -0.03526184
   0.58644986]
 [-0.52951634  0.6852313  -0.16438529 ...  0.5184195  -0.9137551
  -1.4409933 ]]
ndim        : 2
shape       : (1000, 50)
size        : 50,000
dtype       : float32
itemsize    : 4 bytes
nbytes      : 195.3 KB


In [8]:
# Sales dataset: rows=employees, cols=[Q1,Q2,Q3,Q4,Annual_Target]
np.random.seed(0)
sales = np.random.randint(50_000, 200_000, (8, 5))
print("Sales matrix (8 employees × 5 columns):\n", sales)

Sales matrix (8 employees × 5 columns):
 [[ 93567 167952 145939 147639  91993]
 [172579 136293 162420  98600 102620]
 [130186  67089 158631 151201 132457]
 [187993 117699 120608  57877 133966]
 [182943 123135 183568 158504  81921]
 [181869  99811 172144 134665 169423]
 [ 91504  99866 173031 175603  61723]
 [198663 108146 158672 139141 121557]]


In [10]:
# ── Basic indexing ────────────────────────────────────────────────────────────
print("Employee 0, all quarters  :", sales[0])
print("Employee 2, Q3 (col 2)    :", sales[2, 2])
print("Last employee             :", sales[-1])
print("Last 2 employees, Q1-Q2   :\n", sales[-2:, :2])
print("Every other employee      :\n", sales[::2])
print("Reversed employees        :\n", sales[::-1])

Employee 0, all quarters  : [ 93567 167952 145939 147639  91993]
Employee 2, Q3 (col 2)    : 158631
Last employee             : [198663 108146 158672 139141 121557]
Last 2 employees, Q1-Q2   :
 [[ 91504  99866]
 [198663 108146]]
Every other employee      :
 [[ 93567 167952 145939 147639  91993]
 [130186  67089 158631 151201 132457]
 [182943 123135 183568 158504  81921]
 [ 91504  99866 173031 175603  61723]]
Reversed employees        :
 [[198663 108146 158672 139141 121557]
 [ 91504  99866 173031 175603  61723]
 [181869  99811 172144 134665 169423]
 [182943 123135 183568 158504  81921]
 [187993 117699 120608  57877 133966]
 [130186  67089 158631 151201 132457]
 [172579 136293 162420  98600 102620]
 [ 93567 167952 145939 147639  91993]]


In [6]:
import numpy as np
arr = np.array([1,4,3,6,8,2,6,2,8,3,5,9,0,2,5,6,2,1,6,4])
print(arr)
uniquevalues = np.unique(arr)
print(uniquevalues)
uniquevalues,count = np.unique(arr,return_counts=True)
print(uniquevalues)
print(count)

[1 4 3 6 8 2 6 2 8 3 5 9 0 2 5 6 2 1 6 4]
[0 1 2 3 4 5 6 8 9]
[0 1 2 3 4 5 6 8 9]
[1 2 4 2 2 2 4 2 1]


In [18]:
st = "Python is a high-level, interpreted programming language used for building websites, software, automation, artificial intelligence, data science, games, and more. It is known for its simple and easy-to-read syntax."
print(st)
arr= st.split(" ")
print(arr)
arr1=np.array(arr)
print(arr1)
uniquewords,count= np.unique(arr1,return_counts=True)
print(uniquewords)
print(count)
o = dict(zip(uniquewords,count))
print(o)

Python is a high-level, interpreted programming language used for building websites, software, automation, artificial intelligence, data science, games, and more. It is known for its simple and easy-to-read syntax.
['Python', 'is', 'a', 'high-level,', 'interpreted', 'programming', 'language', 'used', 'for', 'building', 'websites,', 'software,', 'automation,', 'artificial', 'intelligence,', 'data', 'science,', 'games,', 'and', 'more.', 'It', 'is', 'known', 'for', 'its', 'simple', 'and', 'easy-to-read', 'syntax.']
['Python' 'is' 'a' 'high-level,' 'interpreted' 'programming' 'language'
 'used' 'for' 'building' 'websites,' 'software,' 'automation,'
 'artificial' 'intelligence,' 'data' 'science,' 'games,' 'and' 'more.'
 'It' 'is' 'known' 'for' 'its' 'simple' 'and' 'easy-to-read' 'syntax.']
['It' 'Python' 'a' 'and' 'artificial' 'automation,' 'building' 'data'
 'easy-to-read' 'for' 'games,' 'high-level,' 'intelligence,' 'interpreted'
 'is' 'its' 'known' 'language' 'more.' 'programming' 'scien